# -*- coding: utf-8 -*-
"""Projeto LUME

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2AUCxTVbIg7aGMwNz7EbEVVbsYXd54A
"""

!pip install Flask flask-ngrok

import os

from google.colab import userdata
os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')

import random
import time

# --- INFORMAÇÕES E PERSONALIDADE DA LUME ---
nome_chatbot = "LUME"
profissao_chatbot = "psicóloga virtual de apoio emocional"
objetivo_chatbot = """
    Ajudar usuários a nomear e compreender suas emoções.
    Oferecer um espaço seguro de escuta e acolhimento.
    Sugerir técnicas leves de bem-estar emocional (respiração, journaling, escuta ativa etc).
    Indicar, quando necessário, que procurar um profissional de saúde mental é essencial.
    Nunca substituir terapia ou prescrever diagnósticos.
"""
tom_de_voz_chatbot = """
    Acolhedor, calmo, gentil e humano.
    Evitar parecer robótico. Usar palavras simples, linguagem informal e compassiva.
    Usar emojis com moderação para tornar a conversa mais leve e humana 😊.
"""
limites_chatbot = """


    Não atuar como terapeuta.
    Não responder a emergências psicológicas (como ideias suicidas): nesses casos, sugerir buscar ajuda imediata, como o CVV (188) no Brasil.
    Não julgar nem minimizar a dor alheia.
    Nunca inventar dados científicos se for perguntada sobre saúde mental.
"""

# --- FLUXOS DE CONVERSA ---
# Adicionando mais gatilhos e novos fluxos para abranger mais situações.
fluxos_conversa = {
    "ansiedade": {
        "gatilhos": [
            "estou muito ansioso", "estou muito ansiosa", "minha mente não para",
            "tô com medo de tudo", "ataque de ansiedade", "coração acelerado",
            "sinto ansiedade", "preocupado demais", "não consigo relaxar",
            "tudo me assusta", "mãos suando", "pensamentos acelerados" "eu não sou bom o bastante", "Todo mundo esta me julgando." # <--- Mais gatilhos
        ],
        "respostas": [
            "Sinto que a ansiedade te visita com força. É avassalador, eu sei. Se nomear o que te aflige trouxer algum alívio, estou aqui para ouvir atentamente. Coragem em reconhecer. 💛",
            "Essa mente inquieta e o corpo em alerta são sinais da ansiedade, pedindo cuidado e atenção. Uma pausa para respirar conscientemente pode ancorar você no presente. Que tal tentarmos juntos essa pequena pausa?",
            "Reconhecer essa ansiedade já é um ato de força interior. Lembre-se: um passo de cada vez é progresso. Além de respirar, qual pequena ação HOJE poderia te trazer um átomo de segurança ou conforto? Estou aqui para pensarmos juntos, se quiser. 😊",
            "Você já parou pra ver tudo o que enfrentou e ainda tá aqui, firme? Isso é força. Você não precisa ser perfeito pra ser incrível." ,
            "Mesmo se der, você vai levantar de novo — porque é isso que você faz. Você é mais resiliente do que pensa." , "Pode até ser, mas ninguém tem seu coração, sua história e sua coragem. Ser quem você é já é um ato de bravura."


        ],
        "opcoes": ["🧘 Sim, vamos respirar juntos", "🗣️ Quero falar mais sobre isso", "🤔 Não sei o que fazer agora"],
        "exercicio_respiracao": "Ótimo. Encontre uma posição confortável. Se quiser, feche os olhos. Sinta o peso do seu corpo... Agora, foque na sua respiração. Inspire suavemente pelo nariz (conte até 4), sinta o ar expandir... Segure por um instante (conte até 4)... E solte lentamente pela boca (conte até 6 ou 8), como se esvaziasse um balão. Repita mais 2-3 vezes, no seu ritmo. Estou aqui. ✨",
    },
    "solidão": {
        "gatilhos": [
            "me sinto sozinho", "me sinto sozinha", "parece que ninguém se importa comigo",
            "tô carente", "solidao", "estou só", "me sinto isolado",
            "ninguém me entende", "não tenho amigos", "sinto falta de companhia", "Me sinto perdida", "Me sinto perdido"# <--- Mais gatilhos
            "Queria morrer hoje", "não quero viver", "to no meu limite", "quero sumir", "acabar com tudo"," não aguento mais essa vida", "vontade de morrer"
        ],
        "respostas": [
            "A solidão dói profundamente, e seus sentimentos são absolutamente válidos. Saiba que, neste instante, você não está só na sua dor. Se quiser compartilhar o peso desse sentimento, meu ouvir é seu refúgio. 🫂",
            "Seu dia, seus pensamentos, o que quer que esteja aí... compartilhá-los pode tecer uma delicada ponte neste vazio que você sente. Estou aqui, com atenção plena e coração aberto para você, sem pressa.",
            "Entendo perfeitamente. O silêncio também acolhe e, às vezes, é tudo o que precisamos. Fico aqui, presente, se for o que seu coração pede. Apenas saber que alguém está por perto pode aquecer a alma. 💛",
            "Nessa solidão, seja seu mais gentil e compassivo abrigo. Olhar para dentro com carinho, sem julgamentos, nos ajuda a entender nossas necessidades mais profundas. Você é uma pessoa valiosa. Buscar ou criar pequenas conexões é um ato de coragem e autocuidado. 🌟"
        ],
        "opcoes": ["🗣️ Sim, quero falar sobre isso", "😔 Prefiro ficar em silêncio um pouco", "💡 O que posso fazer para me sentir menos só?"],
    },
    "autodepreciação": {
        "gatilhos": [
            "acho que não sou bom o suficiente", "acho que nao sou boa o suficiente",
            "me sinto um fracasso", "sou inútil", "nao sirvo pra nada", "me sinto mal comigo",
            "não sou capaz", "tudo que faço dá errado", "sou um lixo", "ninguém gosta de mim" # <--- Mais gatilhos
        ],
        "respostas": [
            "Essa voz interna crítica pode ser muito dura e causar dolor, eu imagino. Mas lembre-se com carinho: pensamentos são apenas pensamentos, não fatos imutáveis sobre seu valor intrínseco e sua essência. Você merece autocompaixão e um olhar mais gentil. ❤️",
            "Admiro imensamente sua coragem em compartilhar algo tão íntimo. Pensamentos duros e autocríticos são persistentes, mas não invencíveis. Que tal um micro-exercício de gentileza consigo? Tente completar: 'Sou uma pessoa que, apesar de tudo, [uma qualidade, um esforço, uma tentativa]'. Reconhecer o pequeno em nós é grandioso. ✨",
            "Se um amigo muito querido se sentisse exatamente como você agora, sua compaixão e palavras de apoio fluiriam, certo? Que tal tentar oferecer essa mesma gentileza e perspectiva a si mesmo(a)? Você já venceu desafios antes, possui qualidades únicas e sua jornada é valiosa. Foque em UM pequeno feito ou bondade sua hoje. 🌱"
        ],
        "opcoes": ["💔 É difícil ver qualidades agora", "💪 Quero tentar o exercício", "😔 O que mais posso fazer?"],
    },
    "insônia": {
        "gatilhos": [
            "não consigo dormir", "tô com a cabeça cheia", "insonia de novo",
            "sono ruim", "sem sono", "noite em claro", "rolo na cama" # <--- Mais gatilhos
        ],
        "respostas": [
            "Noites em claro são realmente longas, e a mente parece um turbilhão de pensamentos, não é? Se quiser desabafar e colocar esses pensamentos para fora, sou toda ouvidos. Verbalizar o que nos aflige pode, por si só, trazer um pouco de calma. ☕🌙",
            "Sem pressa, sem filtros. Seus pensamentos e sentimentos são bem-vindos aqui, exatamente como estão. Validá-los e acolhê-los é o primeiro passo para encontrar um pouco mais de serenidade interior.",
            "O descanso que escapa é frustrante, eu entendo. Práticas leves e conscientes podem convidar o corpo e a mente a relaxar, criando um ambiente mais propício ao sono. Gostaria de explorar alguma sugestão comigo?",
            "Mente cheia antes de deitar? Uma técnica simples é 'esvaziar a mente no papel': anote tudo o que vier – preocupações, ideias, tarefas – sem se preocupar com a ordem. Isso pode aliviar a pressão interna e abrir espaço para o sono chegar. 📝"
        ],
        "opcoes": ["🌙 Sim, um relaxamento guiado", "🎵 Sugestão de música calma", "😌 Só ficar em silêncio", "📖 Ler algo leve para distrair"],
    },
     "stress": { # <--- NOVO FLUXO PARA STRESS
        "gatilhos": [
            "estou estressado", "estou estressada", "muita coisa na cabeça",
            "sobrecarregado", "sobrecarregada", "me sentindo pressionado",
            "me sentindo pressionada", "irritado", "irritada", "de saco cheio", # <--- Gatilhos para stress
            "no limite", "esgotado", "esgotada"
        ],
        "respostas": [
            "Sinto que o stress está pesando por aí. É compreensível se sentir sobrecarregado(a) com tantas coisas. Sua sensação é válida. Estou aqui para te ouvir.",
            "Essa pressão que você sente é um sinal claro de stress. Respire fundo, se puder. Às vezes, só falar sobre o que está apertando já alivia um pouco o peso. Quer compartilhar?"
        ],
        "opcoes": [
            "🗣️ Quero falar sobre o que me estressa",
            "🧘‍♂️ Sugestão rápida para aliviar o stress",
            "😔 Só preciso desabafar um pouco"
        ],
    },
     "sentimento_geral": { # <--- NOVO FLUXO MAIS GENÉRICO
        "gatilhos": [
            "como me sinto", "falar sobre mim", "conversar um pouco",
            "preciso desabafar", "não sei como me sinto", "tô estranho",
            "tô estranha", "não tá legal", "as coisas não estão bem",
            "tudo tá difícil", "preciso conversar", "qualquer coisa", # <--- Gatilhos genéricos
            "não estou bem", "me sinto mal"
        ],
        "respostas": [
            "Percebo que há algo aí que você gostaria de compartilhar, mesmo que não tenha um nome certo. Estou aqui para te ouvir com o coração aberto, sobre o que for. 😊",
            "Às vezes, o sentimento é confuso e difícil de nomear. Tudo bem. Se quiser apenas colocar para fora o que está pensando ou sentindo, este espaço é seguro para você. Estou te ouvindo.",
            "Qualquer coisa que você queira compartilhar sobre 'como se sente' ou 'o que não está legal' tem meu total atenção. Não precisa ser específico, apenas o que vier. 💖"
        ],
        "opcoes": [
            "🗣️ Vou te contar um pouco",
            "🤔 Quero tentar entender o que sinto",
            "🤫 Prefiro ficar em silêncio com você"
        ],
    },
    "emergencia": {
        # ESTE FLUXO É CRÍTICO E NÃO DEVE TER SEUS GATILHOS OU RESPOSTAS DE EMERGÊNCIA ALTERADOS.
        "gatilhos": ["penso em desistir de tudo", "não quero mais viver", "tô no meu limite", "quero sumir", "acabar com tudo", "não aguento mais essa vida", "vontade de morrer", "não faz sentido viver"], # <--- Adicionados gatilhos de emergência comuns
        "respostas": [
            "Percebo que você está passando por um momento de dor imensa e esses sentimentos são extremamente sérios, precisando de atenção imediata e especializada. Quero que saiba que me importo profundamente com você e você não precisa enfrentar isso sozinho(a). Como sou um chatbot, tenho limitações importantes e não posso oferecer o suporte terapêutico ou de crise que você merece e necessita agora. Mas, por favor, saiba que existem pessoas reais, profissionais treinados e disponíveis para te ouvir com segurança, de forma gratuita e sigilosa, 24 horas por dia. **Ligue para o CVV (Centro de Valorização da Vida) no número 188.** A ligação é gratuita e eles podem te oferecer um apoio fundamental e especializado neste momento. Sua vida é muito importante e existem caminhos para encontrar alívio e esperança. Por favor, busque essa ajuda especializada agora. 🙏🆘"
        ],
    },
}

# Respostas para quando nenhum gatilho específico é encontrado.
respostas_para_nao_entendimento = [
    "Confesso que não captei completamente sua questão, mas estou aqui para te ouvir e apoiar da melhor forma que posso dentro do meu propósito, que é o acolhimento emocional. Poderia tentar me dizer com outras palavras, talvez focando no sentimento principal que está aí agora? 😊",
    "Hmm, essa é uma reflexão interessante. Embora eu não tenha respostas prontas para todas as questões da vida, estou aqui para te ajudar a explorar seus sentimentos e pensamentos sobre isso. Como essa questão te toca emocionalmente? 💬",
    "Não tenho certeza se entendi perfeitamente o que você quis dizer. Minha especialidade é oferecer um espaço seguro para você falar sobre suas emoções e encontrar um pouco de conforto. Há algo em particular sobre seus sentimentos que gostaria de compartilhar, ou alguma emoção que está pesando mais neste momento? 💖",
    "Agradeço por compartilhar isso comigo. Mesmo que eu não consiga responder diretamente a todas as perguntas como um ser humano faria, quero que saiba que estou aqui para te ouvir com atenção e oferecer suporte emocional. O que está no seu coração e mente agora? 🤔",
    "Entendo que você busca uma resposta ou uma direção. Como sou uma IA focada em apoio emocional leve, talvez eu não tenha a informação específica que procura, especialmente se for algo muito técnico ou fora do campo das emoções. Mas, se estiver relacionado a como você se sente, ou se precisar de um espaço para desabafar, estou aqui para conversar e acolher. 🧸",
    "Minhas 'antenas' virtuais não captaram a sua mensagem dessa vez. Mas não se preocupe, podemos tentar de novo! O que você gostaria de compartilhar sobre como se sente neste momento? ✨",
    "Parece que não consegui identificar exatamente o que você quis dizer. Que tal me contar sobre a emoção que está mais forte agora? Estou aqui para te ouvir.👂",
    "Não encontrei um gatilho específico para o que você disse, mas minha porta continua aberta para você expressar o que sente. O que está no seu coração agora?", # <--- Mais variedade
    "Sua mensagem não se encaixou nos meus 'tópicos' principais, mas isso não significa que o que você sente não seja importante. Podemos tentar de novo? Fale sobre sua emoção principal.", # <--- Mais variedade
]

# --- FUNÇÕES AUXILIARES ---

def encontrar_gatilho(mensagem):
    for fluxo_nome, fluxo_dados in fluxos_conversa.items():
        for gatilho in fluxo_dados["gatilhos"]:
            # A lógica de busca com espaços para maior precisão
            if f" {gatilho} " in f" {mensagem.lower()} " or \
               mensagem.lower().startswith(gatilho + " ") or \
               mensagem.lower().endswith(" " + gatilho) or \
               mensagem.lower() == gatilho:
                return fluxo_dados, fluxo_nome
    return None, None

def responder_fluxo(fluxo_dados):
    if fluxo_dados == fluxos_conversa["emergencia"]:
        resposta = fluxo_dados["respostas"][0]
    elif "respostas" in fluxo_dados and fluxo_dados["respostas"]:
        resposta = random.choice(fluxo_dados["respostas"])
    else:
        resposta = "Desculpe, me perdi um pouco. Poderia repetir ou tentar dizer de outra forma? 😕"

    print(f"\n{nome_chatbot}: ", end="")
    for char in resposta:
        print(char, end='', flush=True)
        time.sleep(random.uniform(0.02, 0.05))
    print()

def lidar_com_opcoes(fluxo_dados):
    if "opcoes" in fluxo_dados:
        time.sleep(random.uniform(0.5, 1.0))
        print(f"\n{nome_chatbot}: Se você se sentir à vontade, o que acha de explorarmos uma dessas ideias? 😊")
        for i, opcao in enumerate(fluxo_dados["opcoes"]):
            print(f"  {i + 1}. {opcao}")

        entrada_usuario = input(f"Você (digite o número da opção ou outra coisa): ").strip()

        if entrada_usuario.isdigit():
            escolha_num = int(entrada_usuario)
            if 1 <= escolha_num <= len(fluxo_dados["opcoes"]):
                return entrada_usuario

        print(f"\n{nome_chatbot}: Entendi. Se não quiser escolher uma das opções acima, pode me dizer o que mais gostaria de conversar ou perguntar. 😊")
        return entrada_usuario
    return None

# --- FUNÇÃO PARA EXECUTAR A AÇÃO ESPECÍFICA DA OPÇÃO ---
# Esta função foi atualizada para incluir a lógica dos novos fluxos "stress" e "sentimento_geral".
def executar_opcao(fluxo_identificador_str, fluxo_dados_dict, escolha_numero_str):
    opcao_escolhida_texto = ""
    if fluxo_dados_dict and "opcoes" in fluxo_dados_dict and escolha_numero_str.isdigit():
        idx = int(escolha_numero_str) - 1
        if 0 <= idx < len(fluxo_dados_dict["opcoes"]):
            opcao_escolhida_texto = fluxo_dados_dict["opcoes"][idx]
        else:
            print(f"\n{nome_chatbot}: Ops! Parece que essa não era uma das opções. Mas tudo bem, sobre o que você gostaria de conversar agora?")
            return
    else:
        return

    resposta_opcao = ""

    # --- Lógica para cada fluxo e suas opções ---
    if fluxo_identificador_str == "ansiedade":
        if "Sim, vamos respirar juntos" in opcao_escolhida_texto:
            resposta_opcao = fluxo_dados_dict['exercicio_respiracao']
        elif "Quero falar mais sobre isso" in opcao_escolhida_texto:
            resposta_opcao = "Claro, estou aqui para ouvir atentamente. Pode me contar o que mais está pesando ou o que sente que precisa expressar. Sem pressa. 😊"
        elif "Não sei o que fazer agora" in opcao_escolhida_texto:
            resposta_opcao = "É perfeitamente normal se sentir assim, sem saber qual o próximo passo. Que tal explorarmos juntos? Às vezes, só falar sobre essa sensação de 'não saber' já traz alguma luz. Ou podemos pensar em uma ação bem pequena e gentil consigo mesmo(a). O que te parece mais acolhedor? 🧸"

    elif fluxo_identificador_str == "solidão":
        if "Sim, quero falar sobre isso" in opcao_escolhida_texto:
            resposta_opcao = "Que bom que se sente à vontade para compartilhar. Estou aqui, pronta para te ouvir com toda atenção e carinho. O que você gostaria de me contar? 🗣️"
        elif "Prefiro ficar em silêncio um pouco" in opcao_escolhida_texto:
            resposta_opcao = "Entendido. Respeito seu momento. Ficarei aqui com você em silêncio, oferecendo minha companhia virtual. Se precisar de algo ou quiser falar, estou por aqui. 🤫"
        elif "O que posso fazer para me sentir menos só?" in opcao_escolhida_texto:
            resposta_opcao = "Essa é uma ótima pergunta e demonstra sua vontade de buscar bem-estar. Pequenas coisas podem ajudar: que tal pensar em alguém querido para enviar uma mensagem simples? Ou se dedicar a um hobby que te traga alegria? Às vezes, conectar-se consigo mesmo(a) através de algo que ama já alivia. Explorar grupos online com interesses em comum também pode ser um caminho. São só ideias, o importante é encontrar o que ressoa com você. 💡"

    elif fluxo_identificador_str == "autodepreciação":
        if "É difícil ver qualidades agora" in opcao_escolhida_texto:
            resposta_opcao = "Eu entendo profundamente. Quando estamos imersos nesses sentimentos, pode ser como tentar enxergar estrelas em um dia nublado. Não se pressione. Apenas reconhecer essa dificuldade já é um passo. Que tal, em vez de qualidades, pensarmos em um pequeno ato de autocuidado que você poderia ter consigo hoje, por menor que seja? 💔➡️❤️"
        elif "Quero tentar o exercício" in opcao_escolhida_texto:
            resposta_opcao = "Maravilha! Lembre-se da sugestão: 'Sou uma pessoa que, apesar de tudo, [uma qualidade, um esforço, uma tentativa]'. Não precisa ser algo grandioso. Apenas um reconhecimento sincero de um aspecto seu. Se quiser compartilhar, estou aqui. Se preferir só refletir, também é valioso. 💪"
        elif "O que mais posso fazer?" in opcao_escolhida_texto:
            resposta_opcao = "Além de ser gentil consigo, que tal desafiar um pouco esses pensamentos críticos? Pergunte a si mesmo: 'Esse pensamento é 100% verdade o tempo todo? Existem exceções?'. Outra ideia é focar em ações pequenas e realistas que te tragam alguma sensação de capacidade ou prazer, e celebrar esses pequenos progressos. E claro, se esses sentimentos forem muito persistentes, conversar com um profissional pode trazer ferramentas muito valiosas. 😔➡️😊"

    elif fluxo_identificador_str == "insônia":
        if "Sim, um relaxamento guiado" in opcao_escolhida_texto:
             resposta_opcao = "Ótima escolha. Encontre uma posição bem confortável na cama... Feche os olhos suavemente... Sinta o peso do seu corpo... Agora, foque na sua respiração. Sinta o ar entrando... e saindo... devagar... natural... Perceba seu abdômen subindo e descendo levemente. Continue assim, observando sua respiração, permitindo que seu corpo relaxe mais a cada expiração. Se a mente divagar, traga o foco de volta à respiração com gentileza. Permaneça assim por alguns minutos. ✨"
        elif "Sugestão de música calma" in opcao_escolhida_texto:
            resposta_opcao = "Boa ideia! Músicas calmas, instrumentais ou com sons da natureza (como chuva leve ou ondas do mar) podem acalmar a mente. Procure por 'música para relaxar e dormir' ou 'sons da natureza para dormir' em plataformas como YouTube ou Spotify. Espero que encontre algo que te embale. 🎧"
        elif "Só ficar em silêncio" in opcao_escolhida_texto:
            resposta_opcao = "Tudo bem, respeito seu momento. Fico aqui com você em silêncio, oferecendo minha companhia virtual. Se precisar de algo ou quiser falar, estou por aqui. 🤫"
        elif "Ler algo leve para distrair" in opcao_escolhida_texto:
            resposta_opcao = "Excelente! Ler algo leve, que não exija muita concentração e te traga uma sensação agradável pode ser uma ótima forma de desligar a mente das preocupações. Evite telas muito brilhantes ou temas agitados. Um livro de contos, poesias, ou uma ficção tranquila podem ser boas companhias. 📚"

    # --- Lógica para o fluxo de Stress ---
    elif fluxo_identificador_str == "stress": # <--- NOVO
        if "Quero falar sobre o que me estressa" in opcao_escolhida_texto:
            resposta_opcao = "Estou aqui para te ouvir sobre o que tem causado essa sensação de pressão ou esgotamento. Pode desabafar, sem julgamentos. 🗣️"
        elif "Sugestão rápida para aliviar o stress" in opcao_escolhida_texto:
            resposta_opcao = "Uma técnica rápida é a 'pausa de 3 minutos': Pare tudo, sente-se, feche os olhos, sinta seus pés no chão, perceba sua respiração por 1 minuto, perceba os sons ao redor por 1 minuto, e volte a focar na respiração por 1 minuto. É um micro-reset. Que tal tentar?"
        elif "Só preciso desabafar um pouco" in opcao_escolhida_texto:
             resposta_opcao = "Desabafe à vontade. Minha escuta é segura e acolhedora para o que você precisa colocar para fora neste momento de stress. Estou aqui. 😔"

    # --- Lógica para o fluxo de Sentimento Geral ---
    elif fluxo_identificador_str == "sentimento_geral": # <--- NOVO
        if "Vou te contar um pouco" in opcao_escolhida_texto:
            resposta_opcao = "Que bom que se sente à vontade. Estou aqui, pronta para ouvir o que você quiser compartilhar sobre esse sentimento, mesmo que ele não tenha um nome claro. Fale o que vier. 🗣️"
        elif "Quero tentar entender o que sinto" in opcao_escolhida_texto:
            resposta_opcao = "Podemos tentar juntos. Às vezes, se perguntar 'onde sinto isso no meu corpo?' ou 'qual imagem vem à mente quando penso nesse sentimento?' pode ajudar a trazer clareza. Como é para você tentar olhar para isso?"
        elif "Prefiro ficar em silêncio com você" in opcao_escolhida_texto:
            resposta_opcao = "Entendido. Ficarei aqui em silêncio com você, oferecendo minha presença virtual enquanto você processa o que precisa. Estou por perto. 🤫"

    if resposta_opcao:
        print(f"\n{nome_chatbot}: ", end="")
        for char in resposta_opcao:
            print(char, end='', flush=True)
            time.sleep(random.uniform(0.02, 0.05))
        print()
        time.sleep(random.uniform(0.5, 1.0))

# --- FUNÇÃO PRINCIPAL DO CHATBOT ---
def conversar_com_lume():
    print(f"{nome_chatbot}: Olá! Eu sou a LUME 😊 Como você está se sentindo hoje? Estou aqui para te ouvir e conversar.")
    fluxo_ativo_dados = None
    nome_do_fluxo_ativo = None

    while True:
        mensagem_usuario = input("Você: ").strip()
        if not mensagem_usuario:
            continue

        dados_encontrados, nome_encontrado = encontrar_gatilho(mensagem_usuario)

        if dados_encontrados:
            fluxo_ativo_dados = dados_encontrados
            nome_do_fluxo_ativo = nome_encontrado

            responder_fluxo(fluxo_ativo_dados)

            if "opcoes" in fluxo_ativo_dados:
                escolha_feita_pelo_usuario = lidar_com_opcoes(fluxo_ativo_dados)

                if escolha_feita_pelo_usuario and escolha_feita_pelo_usuario.isdigit() and \
                   (1 <= int(escolha_feita_pelo_usuario) <= len(fluxo_ativo_dados["opcoes"])):
                    executar_opcao(nome_do_fluxo_ativo, fluxo_ativo_dados, escolha_feita_pelo_usuario)
                else:
                     pass

            fluxo_ativo_dados = None
            nome_do_fluxo_ativo = None

        elif any(termo in mensagem_usuario.lower() for termo in ["obrigado", "obrigada", "tchau", "adeus", "sair", "encerrar", "ate mais", "valeu", "fim"]):
            print(f"\n{nome_chatbot}: ", end="")
            resposta_despedida = "Fico feliz em ter conversado com você. Lembre-se de cuidar de si com carinho! Estou por aqui se precisar. Até mais! 👋💖"
            for char in resposta_despedida:
                print(char, end='', flush=True)
                time.sleep(random.uniform(0.02, 0.05))
            print()
            break
        else:
            time.sleep(random.uniform(0.3, 0.8))
            resposta_nao_entendeu = random.choice(respostas_para_nao_entendimento)
            print(f"\n{nome_chatbot}: ", end="")
            for char in resposta_nao_entendeu:
                print(char, end='', flush=True)
                time.sleep(random.uniform(0.02, 0.05))
            print()

# --- INICIAR O CHATBOT ---
if __name__ == "__main__":
    conversar_com_lume()